/**
 * The LaTeX renderer (UC09).
 *
 *   CVDocument -> LaTeX -> PDF
 *
 * **One server-controlled template. No user-authored LaTeX, ever.** Every value that reaches the
 * output goes through `escapeLatex` first, and the template itself is the constant below.
 *
 * That is a security boundary, not a formatting preference. LaTeX is a programming language: an
 * unescaped backslash in a person's job title is arbitrary code in a document Joby compiles on its
 * own machine. The escape runs first, so no user string can produce a command sequence — and the
 * compiler additionally runs with shell escape disabled (see `compiler.ts`), because defence in
 * depth is cheap and a single missed call site here would otherwise be remote code execution.
 *
 * LaTeX is a renderer. It is not the domain model, not the source of truth, and nothing downstream
 * of it may be read back into Joby.
 */

import type { CvDocument, CvEntry, CvSection } from './cv-document';

/**
 * Every character that means something to LaTeX, and the text that produces it literally.
 *
 * A single table applied in **one pass**, deliberately. Chained replacements re-process their own
 * output — escaping `\` to `\textbackslash{}` and then escaping braces mangles it — and an escaper
 * whose correctness depends on the order of five regexes is one edit away from a hole.
 */
const LATEX_REPLACEMENTS: Readonly<Record<string, string>> = {
  '\\': '\\textbackslash{}',
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
};

/** Escape one user-supplied string into LaTeX text. */
export function escapeLatex(value: string): string {
  return (
    value
      // Control characters carry no meaning in a CV and can break the compiler.
      .replace(/\p{Cc}/gu, '')
      .replace(/[\\&%$#_{}~^]/g, (character) => LATEX_REPLACEMENTS[character]!)
  );
}

/** A dash-joined period, or nothing. Dates are verbatim from the source and stay that way. */
function period(entry: CvEntry): string {
  if (!entry.startedAt && !entry.endedAt) return '';
  const from = entry.startedAt ? escapeLatex(entry.startedAt) : '';
  const to = entry.endedAt ? escapeLatex(entry.endedAt) : '';
  return from && to ? `${from} -- ${to}` : from || to;
}

function renderEntry(entry: CvEntry): string {
  const title = escapeLatex(entry.title);
  // Emphasis is a positioning signal, so it renders as weight rather than as reordering — the
  // ordering was already decided by the lens's priorities.
  const heading = entry.emphasis === 'emphasised' ? `\\textbf{${title}}` : title;
  const when = period(entry);

  const lines = [`  \\item ${heading}${when ? ` \\hfill {\\small ${when}}` : ''}`];
  if (entry.detail) lines.push(`    \\\\ {\\small ${escapeLatex(entry.detail)}}`);
  return lines.join('\n');
}

function renderSection(section: CvSection): string {
  return [
    `\\section*{${escapeLatex(section.title)}}`,
    '\\begin{itemize}[leftmargin=*, itemsep=2pt, topsep=2pt]',
    section.entries.map(renderEntry).join('\n'),
    '\\end{itemize}',
  ].join('\n');
}

/**
 * The whole template. Deliberately one constant in one place: a template assembled from fragments
 * scattered across the codebase is a template nobody can review for injection.
 */
export function renderCvLatex(document: CvDocument): string {
  const { header } = document;

  const headerLines: string[] = [];
  if (header.fullName) headerLines.push(`{\\LARGE \\textbf{${escapeLatex(header.fullName)}}}\\\\[4pt]`);
  if (header.headline) headerLines.push(`{\\small ${escapeLatex(header.headline)}}\\\\[2pt]`);
  if (header.contact && header.contact.length > 0) {
    headerLines.push(`{\\small ${header.contact.map(escapeLatex).join(' \\textbar{} ')}}`);
  }

  return [
    '% Generated by Joby from an Identity Representation. Do not edit: regenerate.',
    '% Every factual line traces to a confirmed fact in the person\'s Durable Identity.',
    '\\documentclass[11pt,a4paper]{article}',
    '\\usepackage[margin=2cm]{geometry}',
    '\\usepackage{enumitem}',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage{hyperref}',
    '\\hypersetup{hidelinks}',
    '\\pagestyle{empty}',
    '\\setlength{\\parindent}{0pt}',
    '',
    '\\begin{document}',
    '',
    ...(headerLines.length > 0
      ? ['\\begin{center}', headerLines.join('\n'), '\\end{center}', '\\vspace{6pt}']
      : []),
    ...(document.themes.length > 0
      ? [`{\\small ${document.themes.map(escapeLatex).join(' \\textbullet{} ')}}`, '\\vspace{6pt}']
      : []),
    '',
    document.sections.map(renderSection).join('\n\n'),
    '',
    '\\end{document}',
    '',
  ].join('\n');
}
